<a href="https://colab.research.google.com/github/Sony-Dodla/b23_1666/blob/main/LAB3_CW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
fp=open('text.java','w')
fp.write("hello\n")
fp.write("hai\n")
fp.write("this is file handling in python\n")
fp.write("sr university\n")
fp.write("sony dodla\n")
fp.close()
fp=open('text.java','r')
for line in fp:
    print(line)
fp.close()

hello

hai

this is file handling in python

sr university

sony dodla



In [19]:
fp=open('text.java','r')
info=fp.read()
print(info)

hello
hai
this is file handling in python
sr university
sony dodla



In [21]:
fp=open("text.java","r")
line1=fp.readline()
line2=fp.readline()
print("first line:",line1)
print("second line:",line2)

first line: hello

second line: hai



In [23]:
fp=open("text.java","r")
lines=fp.readlines()
print("all lines as list:",lines)
fp.close()

all lines as list: ['hello\n', 'hai\n', 'this is file handling in python\n', 'sr university\n', 'sony dodla\n']


In [28]:
fp=open("text.java","a")
fp.write("appending new data....\n")
fp=open("text.java","r")
print(fp.read())
fp.close()

hello
hai
this is file handling in python
sr university
sony dodla
appending new data....
appending new data....
appending new data....
appending new data....



In [30]:
import csv
with open("data.csv","w",newline="") as fp:
    wr=csv.writer(fp)
    wr.writerows([["name","age","course"],["sony",21,"cse"],["amulya",20,"cse"],["harshitha",21,"cse"]])
from csv import reader
with open("data.csv","r") as fp:
    rd=csv.reader(fp)
    for row in rd:
        print(row)

['name', 'age', 'course']
['sony', '21', 'cse']
['amulya', '20', 'cse']
['harshitha', '21', 'cse']


In [31]:
import numpy as np
#1D array
arr=np.array([1,2,3,4,5])
print("1D ARRAY:",arr)

1D ARRAY: [1 2 3 4 5]


In [33]:
#2D array
arr2=np.array([[1,2,3],[4,5,6]])
print("2D ARRAY:\n",arr2)

2D ARRAY:
 [[1 2 3]
 [4 5 6]]


In [34]:
#zero array
zeros_arr=np.zeros((3,3))
print("ZEROS ARRAY:\n",zeros_arr)

ZEROS ARRAY:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
#ones array
ones_arr=np.ones((2,4))
print("ONES ARRAY:\n",ones_arr)

ONES ARRAY:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
# range of numbers
range_arr=np.arange(1,10,2)
#start stop,step
print("RANGE ARRAY:\n",range_arr)

RANGE ARRAY:
 [1 3 5 7 9]


In [39]:
# random array
rand_arr=np.random.rand(2,3)
print("RANDOM ARRAY:\n",rand_arr)

RANDOM ARRAY:
 [[0.44876249 0.99240431 0.88276511]
 [0.48360968 0.15384891 0.30751628]]


In [40]:
arr=np.array([[1,2,3],[4,5,6]])
print("SHAPE OF ARRAY:",arr.shape)
print("dimension:",arr.ndim)
print("size:",arr.size)
print("data type:",arr.dtype)
print("item size:",arr.itemsize)

SHAPE OF ARRAY: (2, 3)
dimension: 2
size: 6
data type: int64
item size: 8


In [42]:
arr=np.array([10,20,30,40,50])
print("first element:",arr[0])
print("last element:",arr[-1])
print("slice[1:4]:",arr[1:4])
print("every second element:",arr[::2])

first element: 10
last element: 50
slice[1:4]: [20 30 40]
every second element: [10 30 50]


In [44]:
#2D indexing
arr2=np.array([[1,2,3],[4,5,6]])
print("element at row 1,col 2:",arr2[0,1])
print("second row :",arr2[1,:])
print("second col:",arr2[:,1])

element at row 1,col 2: 2
second row : [4 5 6]
second col: [2 5]


In [45]:
arr=np.array([[1,2,3],[4,5,6]])
print("before reshaping:\n",arr)
arr=arr.reshape(3,2)
print("after reshaping:\n",arr)

before reshaping:
 [[1 2 3]
 [4 5 6]]
after reshaping:
 [[1 2]
 [3 4]
 [5 6]]


In [49]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Power:",a**2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


In [46]:
#Aggregate functions
arr=np.array([[1,2,3],[4,5,6]])
print("sum:",np.sum(arr))
print("min:",np.min(arr))
print("max:",np.max(arr))
print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("standard deviation:",np.std(arr))
print("sum of axis 0:",np.sum(arr,axis=0))
print("sum of axis 1:",np.sum(arr,axis=1))

sum: 21
min: 1
max: 6
mean: 3.5
median: 3.5
standard deviation: 1.707825127659933
sum of axis 0: [5 7 9]
sum of axis 1: [ 6 15]


In [48]:
arr=np.array([0,np.pi/2,np.pi/3,np.pi])
print("sin values:",np.sin(arr))
print("cos values:",np.cos(arr))
print("square root:",np.sqrt(arr))
print("exponential:",np.exp(arr))
print("log values:",np.log(arr))
print("tan values:",np.tan(arr))

sin values: [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]
cos values: [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]
square root: [0.         1.25331414 1.02332671 1.77245385]
exponential: [ 1.          4.81047738  2.84965391 23.14069263]
log values: [      -inf 0.45158271 0.0461176  1.14472989]
tan values: [ 0.00000000e+00  1.63312394e+16  1.73205081e+00 -1.22464680e-16]


/tmp/ipython-input-1048097776.py:6: RuntimeWarning: divide by zero encountered in log
  print("log values:",np.log(arr))


In [50]:
#broadcasting
a=np.array([1,2,3])
b=5
print("Add scalar to array :",a+b)
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print("broadcasting:\n",c+d)

Add scalar to array : [6 7 8]
broadcasting:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [53]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("matrix multiplication:\n",np.dot(A,B))
print("Transpose:\n",A.T)
print("Inverse:\n",np.linalg.inv(A))
print("Determinant:\n",np.linalg.det(A))

matrix multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant:
 -2.0000000000000004


In [55]:
import numpy as np
marks=np.array([[85,92,65],
               [54,44,25],
               [56,52,75]])
print("average marks per student:",np.mean(marks,axis=1))
print("average marks per subject:",np.mean(marks,axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

average marks per student: [80.66666667 41.         61.        ]
average marks per subject: [65.         62.66666667 55.        ]
Highest marks in each subject: [85 92 75]
Lowest marks in each subject: [54 44 25]
