<a href="https://colab.research.google.com/github/Sony-Dodla/b23_1666/blob/main/LAB_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([[98,99,97],[89,87,94],[79,89,86]])
print(arr)

[[98 99 97]
 [89 87 94]
 [79 89 86]]


In [3]:
for i in range(0,3):
  print(arr[i])

[98 99 97]
[89 87 94]
[79 89 86]


## Calculate average, minimum, and maximum marks

In [4]:
total_avg=np.mean(arr)
print(total_avg)
maxi=np.max(arr)
print(maxi)
mini=np.min(arr)
print(mini)

90.88888888888889
99
79


In [5]:
average_per_student = np.mean(arr, axis=1)
min_per_student = np.min(arr, axis=1)
max_per_student = np.max(arr, axis=1)
for i in range(len(arr)):
    print(f"Student {i+1}: Marks = {arr[i]}, Avg = {average_per_student[i]:.2f}, Min = {min_per_student[i]}, Max = {max_per_student[i]}")

Student 1: Marks = [98 99 97], Avg = 98.00, Min = 97, Max = 99
Student 2: Marks = [89 87 94], Avg = 90.00, Min = 87, Max = 94
Student 3: Marks = [79 89 86], Avg = 84.67, Min = 79, Max = 89


##Use slicing to retrieve marks of specific students

In [6]:
print("\nMarks of Student 2:\n", arr[1:2])


Marks of Student 2:
 [[89 87 94]]


##Use boolean indexing to find students scoring above 80

In [7]:
above_80 = arr > 80
print("\n Boolean Array (Scores > 80):\n", above_80)


 Boolean Array (Scores > 80):
 [[ True  True  True]
 [ True  True  True]
 [False  True  True]]


##Reshape the array to observe subject-wise performance

In [8]:
subject_wise = arr.T
print("\n Subject-wise Performance (Rows = Subjects):\n", subject_wise)


 Subject-wise Performance (Rows = Subjects):
 [[98 89 79]
 [99 87 89]
 [97 94 86]]
